#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GoMoblinPortal")]
	public partial class PortalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PortalDataContext() : 
				base(global::DAL.Properties.Settings.Default.GoMoblinPortalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PortalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Backend_Settings_Get")]
		public ISingleResult<Backend_Settings_GetResult> Backend_Settings_Get()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Backend_Settings_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertHttpRequest")]
		public int InsertHttpRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sessionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserHostAddress", DbType="VarChar(100)")] string userHostAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Device", DbType="NVarChar(250)")] string device, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UrlReferrer", DbType="NVarChar(MAX)")] string urlReferrer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestUrl", DbType="NVarChar(MAX)")] string requestUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MachineId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> machineId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cookies", DbType="NVarChar(MAX)")] string cookies, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QueryString", DbType="NVarChar(MAX)")] string queryString, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsNewSeession", DbType="Bit")] System.Nullable<bool> isNewSeession)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionId, userHostAddress, userId, device, urlReferrer, requestUrl, machineId, cookies, queryString, isNewSeession);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WebSite_GetResource_Value")]
		public int WebSite_GetResource_Value([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Culture", DbType="VarChar(10)")] string culture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameOut", DbType="NVarChar(MAX)")] ref string nameOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CultureOut", DbType="VarChar(10)")] ref string cultureOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValueOut", DbType="NVarChar(MAX)")] ref string valueOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), culture, name, nameOut, cultureOut, valueOut);
			nameOut = ((string)(result.GetParameterValue(2)));
			cultureOut = ((string)(result.GetParameterValue(3)));
			valueOut = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.WebSite_GetResources_Value")]
		public ISingleResult<WebSite_GetResources_ValueResult> WebSite_GetResources_Value()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<WebSite_GetResources_ValueResult>)(result.ReturnValue));
		}
	}
	
	public partial class Backend_Settings_GetResult
	{
		
		private System.Guid _Id;
		
		private byte _DocumentTypeId;
		
		private string _Json;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<long> _Tstamp;
		
		private bool _IsDeleted;
		
		public Backend_Settings_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentTypeId", DbType="TinyInt NOT NULL")]
		public byte DocumentTypeId
		{
			get
			{
				return this._DocumentTypeId;
			}
			set
			{
				if ((this._DocumentTypeId != value))
				{
					this._DocumentTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Json", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Json
		{
			get
			{
				return this._Json;
			}
			set
			{
				if ((this._Json != value))
				{
					this._Json = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tstamp", DbType="BigInt")]
		public System.Nullable<long> Tstamp
		{
			get
			{
				return this._Tstamp;
			}
			set
			{
				if ((this._Tstamp != value))
				{
					this._Tstamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class WebSite_GetResources_ValueResult
	{
		
		private string _Culture;
		
		private string _Name;
		
		private string _Value;
		
		public WebSite_GetResources_ValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Culture", DbType="NVarChar(MAX)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this._Culture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
